sudo: required

language: java

services:
  - docker

addons:
  chrome: stable
  browserstack:
    username: "${BROWSERSTACK_USER}"
    access_key: "${BROWSERSTACK_PASS}"

before_install:

- echo $USER

- echo "********* Starting Up Docker Image ********";
- cd ./docker/
- docker-compose up &

# get IP Address for remote selenium grid
- ifconfig

script:
- echo "********* Setting up Tests ********";
- npm install
- npm install -g chromedriver@2.46.0
- pwd
- cd ../e2e_test/webdriver-test/
- npm test
- echo "********* Running Tests ********";
- echo "********* Completed Running Tests ********";
#- echo "********* Shutting Down Docker Images ********";
#- cd ../../docker/
#- docker-compose down
